version: '3.8'

services:
  # MongoDB Database
  mongodb:
    image: mongo:6.0
    container_name: agrolens-mongodb
    restart: unless-stopped
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: password123
      MONGO_INITDB_DATABASE: agrolens
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    networks:
      - agrolens-network

  # Backend API
  backend:
    build: ./backend
    container_name: agrolens-backend
    restart: unless-stopped
    environment:
      NODE_ENV: production
      MONGODB_URI: mongodb://admin:password123@mongodb:27017/agrolens?authSource=admin
      JWT_SECRET: your_super_secret_jwt_key_here
      PORT: 5000
    ports:
      - "5000:5000"
    depends_on:
      - mongodb
    networks:
      - agrolens-network

  # AI Service
  ai-service:
    build: ./ai-service
    container_name: agrolens-ai-service
    restart: unless-stopped
    environment:
      FLASK_ENV: production
      PORT: 5001
    ports:
      - "5001:5001"
    networks:
      - agrolens-network

  # Frontend
  frontend:
    build: ./frontend
    container_name: agrolens-frontend
    restart: unless-stopped
    environment:
      REACT_APP_API_URL: http://localhost:5000/api
      REACT_APP_AI_SERVICE_URL: http://localhost:5001
    ports:
      - "3000:3000"
    depends_on:
      - backend
      - ai-service
    networks:
      - agrolens-network

volumes:
  mongodb_data:

networks:
  agrolens-network:
    driver: bridge